### ISSUE TITLE
key `directory` is not working

### ISSUE THREAD

**Issue by rajeshg-vcloudx** [SpicyPizza/create-envfile#9] opened 2021-01-27 11:08 UTC
As per doc, this key should set the directory in which you want to create env file. However, it is creating env file at $GITHUB_WORKSPACE even after specifying directory or even full path.

**Comment by abcfy2** [comment] 2021-02-04 13:50
Same issue.

**Comment by AngelOnFira** [comment] 2021-02-18 13:42
@rajeshg-vcloudx @abcfy2 Were you using the @master or @v1 for the Action? I think this is because I haven't updated the tag yet. Hopefully, I can do this in the next few days. If the issue is separate, I'll look into it further.

**Comment by baileytincher** [comment] 2021-04-18 18:06
Project seems abandoned. I forked and fixed the action https://github.com/marketplace/actions/create-dotenv-file

**Comment by AngelOnFira** [comment] 2021-04-18 20:48
Working on updating to new version today, closing as there is nothing else to do.

**Closed by AngelOnFira** 2021-04-18 20:48 UTC
